[package]
name = "MonarchDbBackend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.19.2"
rocket = "0.4.10"
async-graphql = "3.0.31"
jwt = "0.16.0"
dotenv = "0.15.0"

